# Javascript Node CircleCI 2.0 configuration file
#
version: 2.1

executors:
  job-executor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

jobs:
  build:
    executor: job-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run build
          command: yarn build
      - run:
          name: Run bundlesize
          command: yarn bundlesize
  lint:
    executor: job-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Run eslint
          command: yarn lint
      - run:
          name: Run type-check
          command: yarn tsc

  test:
    executor: job-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn jest

  cypress:
    docker:
      - image: cypress/browsers:node12.6.0-chrome75
        environment:
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Cypress
          command: yarn cypress:ci

workflows:
  version: 2
  build:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - cypress
