/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaletteRouteImport } from './routes/palette'
import { Route as ApiPageRouteImport } from './routes/api-page'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSlashCommandRouteImport } from './routes/api/slash-command'
import { Route as ApiAreTheyRouteImport } from './routes/api/are-they'

const PaletteRoute = PaletteRouteImport.update({
  id: '/palette',
  path: '/palette',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPageRoute = ApiPageRouteImport.update({
  id: '/api-page',
  path: '/api-page',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlashCommandRoute = ApiSlashCommandRouteImport.update({
  id: '/api/slash-command',
  path: '/api/slash-command',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAreTheyRoute = ApiAreTheyRouteImport.update({
  id: '/api/are-they',
  path: '/api/are-they',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-page': typeof ApiPageRoute
  '/palette': typeof PaletteRoute
  '/api/are-they': typeof ApiAreTheyRoute
  '/api/slash-command': typeof ApiSlashCommandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-page': typeof ApiPageRoute
  '/palette': typeof PaletteRoute
  '/api/are-they': typeof ApiAreTheyRoute
  '/api/slash-command': typeof ApiSlashCommandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-page': typeof ApiPageRoute
  '/palette': typeof PaletteRoute
  '/api/are-they': typeof ApiAreTheyRoute
  '/api/slash-command': typeof ApiSlashCommandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-page'
    | '/palette'
    | '/api/are-they'
    | '/api/slash-command'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-page'
    | '/palette'
    | '/api/are-they'
    | '/api/slash-command'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-page'
    | '/palette'
    | '/api/are-they'
    | '/api/slash-command'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiPageRoute: typeof ApiPageRoute
  PaletteRoute: typeof PaletteRoute
  ApiAreTheyRoute: typeof ApiAreTheyRoute
  ApiSlashCommandRoute: typeof ApiSlashCommandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/palette': {
      id: '/palette'
      path: '/palette'
      fullPath: '/palette'
      preLoaderRoute: typeof PaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-page': {
      id: '/api-page'
      path: '/api-page'
      fullPath: '/api-page'
      preLoaderRoute: typeof ApiPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slash-command': {
      id: '/api/slash-command'
      path: '/api/slash-command'
      fullPath: '/api/slash-command'
      preLoaderRoute: typeof ApiSlashCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/are-they': {
      id: '/api/are-they'
      path: '/api/are-they'
      fullPath: '/api/are-they'
      preLoaderRoute: typeof ApiAreTheyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiPageRoute: ApiPageRoute,
  PaletteRoute: PaletteRoute,
  ApiAreTheyRoute: ApiAreTheyRoute,
  ApiSlashCommandRoute: ApiSlashCommandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
