name: Checks

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.x]
    env:
      CYPRESS_CACHE_FOLDER: ./node_modules/cypress
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.x]
    env:
      CYPRESS_CACHE_FOLDER: ./node_modules/cypress
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run eslint
        run: yarn lint

  cypress-percy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.x]
    env:
      CYPRESS_CACHE_FOLDER: ./node_modules/cypress
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Node modules cache
        uses: actions/cache@v2
        id: node_modules_cache_id
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Wait for Netlify
        uses: hharnisc/wait-for-netlify-action@4.0.1
        id: waitForDeployment
        with:
          site_id: ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

      - name: Percy Test
        run: yarn cypress:run
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_BASE_URL: ${{ steps.waitForDeployment.outputs.url }}

  jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.x]
    env:
      CYPRESS_CACHE_FOLDER: ./node_modules/cypress
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: node -v
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run jest
        run: yarn jest
